### ISSUE TITLE
每个人索引的创建是需要自己爬然后传到docs里还是run一下summary.py就好了

### ISSUE THREAD

**Issue by KangKaneYang** [L-M-Sherlock/ZhiHuLegend#2]
我本地run了一下summary.py发现打印出来的answers是空的。。。顺便如果可以的话请求加上李新野的回答，他的username是sinya，顺便补充曾博之前用过的几个号：bboczeng, bboczeng2, tanchaobo2, huo-gu-lao-shi-ren, ye-bo-zs, greypuppy, xiao-ye-bo-78, xiao-xiao-ye-bo, bei-ji-xiong-43-25, bei-li-kou-58, fu-zhi-bo-95

**Comment by L-M-Sherlock** [comment]
> 我本地run了一下summary.py发现打印出来的answers是空的

因为你没有把原数据拉下来。原数据是这样的：https://github.com/L-M-Sherlock/ZhiHuArchive/tree/main/article

**Comment by L-M-Sherlock** [comment]
李新野：https://l-m-sherlock.github.io/ZhiHuLegend/sinya.html

**Comment by L-M-Sherlock** [comment]
bboczeng 这个号的内容在我备份后被知乎删完了，备份内容我已经发给勃勃了。

**Comment by KangKaneYang** [comment]
十分感谢对李新野知乎内容的补充！

**Comment by L-M-Sherlock** [comment]
bobo剩下这些号的文章+回答还有近两千篇，今晚前应该可以更新好。

**Comment by L-M-Sherlock** [comment]
4c0744c 已加入。
